### ISSUE TITLE
Dropdown animation flickers on Firefox.

### ISSUE THREAD

**Issue by CMD-Forum** [CMD-Forum/cmd-forum#3]
Dropdown animations work fine on _Chromium_ browsers (Chrome, MS Edge), but on _Firefox_ the animations flicker awkwardly.

**Comment by JamsterJava** [comment]
Dropdowns are being completely redesigned, so this is being closed as not planned. Hopefully it doesn't have to be reopened.

**Comment by JamsterJava** [comment]
Dropdowns have been completely redone since, this issue no longer applys.
